### ISSUE TITLE
Some files not found in first production run

### ISSUE THREAD

**Issue by cisaacstern** [pangeo-forge/cesm-atm-025deg-feedstock#2]
@paigem, it looks like we're hitting some `FileNotFoundError`s in https://pangeo-forge.org/dashboard/recipe-run/338.

Do the reported urls appear to be ones at which real data exists? If not, perhaps this is an issue with the file pattern?

**Comment by rabernat** [comment]
I would say that our current logging was very effective at helping us find and fix a problem.

Will the cache be reused between separate runs?

**Comment by cisaacstern** [comment]
Yes, a definite vote of confidence for our logging!

And yes, the cache is reused.

**Comment by paigem** [comment]
Yes, the logging told me exactly where to look for the missing files! And the files were indeed missing, so it was a problem from the source data location.

**Comment by cisaacstern** [comment]
@paigem, does this look like the expected full dataset?

```python
# To get an interactive `ds`, you can run this yourself in any notebook w/ fsspec + xarray installed

import fsspec
import xarray as xr

url = "https://ncsa.osn.xsede.org/Pangeo/pangeo-forge/cesm-atm-025deg-feedstock/cesm-atm-025deg.zarr"
mapper = fsspec.get_mapper(url)
ds = xr.open_zarr(url, consolidated=True)
ds
```

<details>

<summary>Dataset details</summary >

```
<xarray.Dataset>
Dimensions:    (time: 73, lat: 768, lon: 1152, ilev: 31, lev: 30, nbnd: 2)
Coordinates:
  * ilev       (ilev) float64 2.255 5.032 10.16 18.56 ... 967.5 985.1 1e+03
  * lat        (lat) float64 -90.0 -89.77 -89.53 -89.3 ... 89.3 89.53 89.77 90.0
  * lev        (lev) float64 3.643 7.595 14.36 24.61 ... 936.2 957.5 976.3 992.6
  * lon        (lon) float64 0.0 0.3125 0.625 0.9375 ... 358.8 359.1 359.4 359.7
  * time       (time) object 0051-01-01 00:00:00 ... 0051-03-14 00:00:00
Dimensions without coordinates: nbnd
Data variables: (12/35)
    FLDS       (time, lat, lon) float32 dask.array<chunksize=(73, 768, 1152), meta=np.ndarray>
    FSNS       (time, lat, lon) float32 dask.array<chunksize=(73, 768, 1152), meta=np.ndarray>
    LHFLX      (time, lat, lon) float32 dask.array<chunksize=(73, 768, 1152), meta=np.ndarray>
    P0         float64 ...
    PSL        (time, lat, lon) float32 dask.array<chunksize=(73, 768, 1152), meta=np.ndarray>
    SHFLX      (time, lat, lon) float32 dask.array<chunksize=(73, 768, 1152), meta=np.ndarray>
    ...         ...
    nsteph     (time) float64 dask.array<chunksize=(73,), meta=np.ndarray>
    ntrk       float64 ...
    ntrm       float64 ...
    ntrn       float64 ...
    sol_tsi    (time) float64 dask.array<chunksize=(73,), meta=np.ndarray>
    time_bnds  (time, nbnd) object dask.array<chunksize=(73, 2), meta=np.ndarray>
Attributes: (12/18)
    Conventions:      CF-1.0
    TITLE:            REMAPPED: UNSET                                        ...
    Version:          $Name$
    case:             hybrid_v5_rel04_BC5_ne120_t12_pop62                    ...
    creation_date:    Fri Sep 19 14:46:57 MDT 2014
    host:             ys2738          
    ...               ...
    revision_Id:      $Id$
    separator1:       ------- SOURCE FILE ATTRIBUTES --------
    separator2:       ---------------------------------------
    source:           CAM
    title:            UNSET                                                  ...
    topography_file:  /glade/p/cesm/cseg//inputdata/atm/cam/topo/USGS_gtopo30...
```

</details>

A few notes:

- This is the dataset which was automatically built following merge of https://github.com/pangeo-forge/cesm-atm-025deg-feedstock/pull/3
- The associated deployment is technically ["failing"](https://github.com/pangeo-forge/cesm-atm-025deg-feedstock/deployments), however unlike the `FileNotFoundError`, the error which caused this deployment to be marked as a failure is not surfaced by the unfiltered logs displayed on the [associated recipe run](https://pangeo-forge.org/dashboard/recipe-run/340). A resolution to https://github.com/pangeo-forge/pangeo-forge.org/issues/63 would make this error discoverable on pangeo-forge.org; I'm working on this in https://github.com/pangeo-forge/pangeo-forge.org/pull/88.

- In the absence of the ability to filter logs on pangeo-forge.org, I logged into the Pangeo Forge Cloud backend to inspect the logs directly, and I'm not convinced that this error (see details below) is relevant to the the dataset itself. Generally, if a dataset build has errored, the target path is not openable, whereas this dataset _is_ openable. This error may be some type of incidental infrastructure teardown issue, or something of that nature, which did not affect the dataset build itself.

<details>

<summary>Error details</summary>

```
Unexpected error: OSError('Timed out trying to connect to tcp://dask-jovyan-af92d63f-6.pangeo-forge-columbia-staging-bakery:8786 after 30 s')
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/distributed/comm/tcp.py", line 398, in connect
    stream = await self.client.connect(
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/tornado/tcpclient.py", line 275, in connect
    af, addr, stream = await connector.start(connect_timeout=timeout)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/distributed/comm/core.py", line 284, in connect
    comm = await asyncio.wait_for(
  File "/srv/conda/envs/notebook/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/prefect/engine/flow_runner.py", line 661, in get_flow_run_state
    assert isinstance(final_states, dict)
  File "/srv/conda/envs/notebook/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/prefect/executors/dask.py", line 237, in start
    self._post_start_yield()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/distributed/deploy/spec.py", line 445, in __exit__
    super().__exit__(typ, value, traceback)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/distributed/deploy/cluster.py", line 468, in __exit__
    return self.sync(self.__aexit__, typ, value, traceback)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/distributed/deploy/cluster.py", line 258, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/distributed/utils.py", line 332, in sync
    raise exc.with_traceback(tb)
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/distributed/utils.py", line 315, in f
    result[0] = yield future
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/distributed/deploy/cluster.py", line 477, in __aexit__
    await f
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/distributed/deploy/spec.py", line 417, in _close
    await self._correct_state()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/distributed/deploy/spec.py", line 332, in _correct_state_internal
    await self.scheduler_comm.retire_workers(workers=list(to_close))
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/distributed/core.py", line 817, in send_recv_from_rpc
    comm = await self.live_comm()
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/distributed/core.py", line 774, in live_comm
    comm = await connect(
  File "/srv/conda/envs/notebook/lib/python3.9/site-packages/distributed/comm/core.py", line 308, in connect
    raise OSError(
OSError: Timed out trying to connect to tcp://dask-jovyan-af92d63f-6.pangeo-forge-columbia-staging-bakery:8786 after 30 s
```

</details>

**Comment by rabernat** [comment]
Each variable appears to have only one chunk. That seems like a red flag.

https://github.com/pangeo-forge/cesm-atm-025deg-feedstock/blob/265a50676396e71172548ceab70d06259855419f/feedstock/recipe.py#L35

I would guess that only one input has been processed.

**Comment by paigem** [comment]
I was just typing up the same response @rabernat! Yes, the time dimension is only of length 73, which is a single chunk. 

The test data that I checked off on [in this comment](https://github.com/pangeo-forge/staged-recipes/pull/137#issuecomment-1147871960) had time of length 730, so for that run we were able to get past the first chunk.

**Comment by paigem** [comment]
@cisaacstern I am just going through the variables and will probably add a few to the recipe. Should I do that now before we spend more time figuring out why only a single chunk was processed?

**Comment by cisaacstern** [comment]
> I would guess that only one input has been processed.

A-ha. Yes that makes sense.

> I am just going through the variables and will probably add a few to the recipe. Should I do that now before we spend more time figuring out why only a single chunk was processed?

@paigem, yes why don't you go ahead and open a new PR to add variables. That will give us an opportunity to re-run the production dataset and see if we get the same error. (Which can help us clarify if this was an incidental infrastructure issue, or something inherent to the recipe.)

In the meantime, I'll close this issue, because the actual problem it documents (`FileNotFoundError`) was resolved. If/when the next production run errors, we can open a new issue to track that.
